//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makerlab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingPrintError
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BookingId { get; set; }
        public string ErrorType { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int User_Id { get; set; }
        public int Booking_Id { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual User User { get; set; }
    }
}
