//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makerlab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Booking = new HashSet<Booking>();
            this.BookingPrintError = new HashSet<BookingPrintError>();
        }
    
        public int Id { get; set; }
        public int UserRoleId { get; set; }
        public string StudieNumber { get; set; }
        public int AccessCard { get; set; }
        public int UserRole_Id { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual ICollection<BookingPrintError> BookingPrintError { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
