//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makerbot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.BookingPrintError = new HashSet<BookingPrintError>();
        }
    
        public int Id { get; set; }
        public int PrinterId { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Printer Printer { get; set; }
        public virtual ICollection<BookingPrintError> BookingPrintError { get; set; }
    }
}
